#!/usr/bin/env bash

###############################################################################
# Includes and defines

packageName=bg-dev

source /usr/lib/bg_core.sh
import bg_pkgRepo.sh ;$L1;$L2
import bg_creqs.sh   ;$L1;$L2

cmds="update clean"
cmdlineSyntax="[-q|--quiet] [-v|--verbose] [-f|--force] [-u|--user=<user>]  <cmd>|update"

###############################################################################
# Command manpage
# usage: bg-pkgRepo [-q|--quiet] [-v|--verbose] [-f|--force] [-u|--user=<user>]  <cmd>
# <one line description...>
# <description...>
#
# Options:
# Params:
# See Also:


###############################################################################
# Functions

# this is invoked by oob_invokeOutOfBandSystem when -hb is the first param
# The bash completion script calls this get the list of possible words.
function oob_printBashCompletion()
{
	bgBCParse "$cmdlineSyntax" "$@"; set -- "${posWords[@]:1}"

	case $completingArgName in
		'<user>') awk -F: '{print $1}' /etc/passwd ;;
	esac
}

# Use this function to provide BC suggestions for positional parameters
# see man bg-overviewOutOfBandScriptFunctions for details
function oob_helpMode()
{
	local -A clInput; bgCmdlineParse -RclInput "$cmdlineSyntax" "$@"; shift "${clInput[shiftCount]}"
	case ${clInput[cmd]:-main} in
		main)  man "$(basename $0)" ;;
		*)     man "$(basename $0)" ;;
	esac
}


###############################################################################
# Main script

# default values for parameters
verbosity=1
forceFlag=""
userName=""
oob_invokeOutOfBandSystem "$@"
while [ $# -gt 0 ]; do case $1 in
	-v | --verbose)  ((verbosity++)) ;;
	-q | --quiet)    ((verbosity--)) ;;
	--verbosity*)    bgOptionGetOpt val: verbosity "$@" && shift ;;
	-f  | --force)   forceFlag="-f" ;;
	-u* | --user)    bgOptionGetOpt val: userName "$@" && shift ;;
	*)  bgOptionsEndLoop "$@" && break; set -- "${bgOptionsExpandedOpts[@]}"; esac; shift;
done
cmd="$1"; shift

case ${cmd:-cmd1} in
	update) pkgRepoUpdate       "$@" ;;
	clean)  pkgRepoCleanStaging "$@" ;;
	*) assertError -v subCmd:cmd "Unknown sub command." ;;
esac
